id: P002945
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:30:05.627084
source_metadata:
  id: bdr:W1KG9728
  title: ཡེ་ཤེས་ཀྱི་མགོན་པོ་བེར་ནག་ཅན་ལྕམ་དྲལ་གྱི་བསྙེན་སྒྲུབ་སྐོར།
  author: ''
  volumes:
    63ed7889c1a44ce6ba3421bf5d5495ab:
      image_group_id: I1KG9741
      title: ''
      volume_number: 1
      total_pages: 476
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
